# Example configuration file for corsarofanner

# The number of threads that the fanner should use. Make sure any
# downstream corsarotrace instances also are configured to use this
# number of threads...
threads: 4

# Location to write our log file to, if run with log mode set to 'file'
logfilename: "/var/log/corsarofanner.log"

# Location to write out statistic files to. Comment out to disable stat
# logging.
statfilename: "/tmp/fannerstatistics"

# The name of the ZeroMQ queue that packets should be received from
subqueuename: "tcp://10.0.0.1:6002"

# The basename of the ZeroMQ queues that packets will be re-published onto
pubqueuename: "ipc:///tmp/corsarofanner"

# High water mark for the receiving ZeroMQ queue
inputhwm: 50

# High water mark for the publishing ZeroMQ queues
outputhwm: 50

