# Example configuration file for corsarotagger

# Location to write our log file to, if run with log mode set to 'file'
logfilename: "/var/log/corsarotagger.log"

# Libtrace URI describing where our packets are going to be read from
# In this case, we're receiving packets via the nDAG protocol on interface
# ens4 by joining a multicast group 225.255.0.1:44000
inputuri: "ndag:ens4,225.225.0.1,44000"

# Enable promiscuous mode on our capture source
promisc: no

# Use a bidirectional flow hash to assign packets to processing threads.
dohashing: no

# Discard all packets that do NOT match this BPF filterstring
basicfilter: "icmp or tcp or udp"

# Number of packet processing threads to use
pktthreads: 8

# Number of tagging worker threads to use
tagthreads: 4

# All of our captured packets are standard Ethernet with no extra meta-data
# and come from an ERF-based source (e.g. Endace DAG)
# so we can get tell corsarowdcap to assume a constant ERF framing size of 18.
# This offers some performance improvements at high packet rates.
# Comment out this option if you are not using an ERF-based source or think
# that your ERF framing size is unlikely to be a constant value.
consterfframing: 18

# The ZeroMQ queue that our tagged packets will be written to
pubqueuename: "ipc:///tmp/corsarotagger"


# Configuration for specific tag-data providers that are supported by
# this tool. Basic tagging will always take place, regardless of what is
# included in this section of the config file.
# Other tagging will only occur if the relevant provider is correctly
# configured here.
tagproviders:

#  Use Maxmind geo-location data to tag captured packets
   - maxmind:
       blocksfile: "/path/to/GeoLiteCity-Blocks.csv.gz"
       locationsfile: "/path/to/GeoLiteCity-Location.csv.gz"

#  Use Netacuity Edge geo-location data to tag captured packets
   - netacq-edge:
       blocksfile: "/path/to/netacq-4-blocks.latest.csv.gz"
       locationsfile: "/path/to/netacq/netacq-4-locations.latest.csv.gz"

#  Use Prefix2ASN data to tag captured packets with their source ASN
   - pfx2as:
       prefixfile: "/path/to/prefixasn/routeviews-rv2-20180923-1200.pfx2as.gz"

